### PR TITLE
Updated BER tag encoding following the ISO 7816 standard

### PR DESCRIPTION
**Pull request by OmegaRelay**
This commit fixes BER tag encoding for tag values greater than 30, also fixes encoding the constructed bit.

 — The value 00 indicates a DO of the universal class.
 — The value 01 indicates a DO of the application class.
 — The value 10 indicates a DO of the context-specific class.
 — The value 11 indicates a DO of the private class.
Bit b6 of the first byte of the tag field indicates an encoding (see E.3).
If bits b5 to b1 of the first byte of the tag field are not all set to 1, then they encode a tag number from
zero to thirty and the tag field consists of a single byte. Tag number 0 is precluded in the universal class.
Otherwise (bits b5 to b1 all set to 1), the tag field continues on one or more subsequent bytes.
 — Bit b8 of each subsequent byte shall be set to 1, unless it is the last subsequent byte.
 — Bits b7 to b1 of the first subsequent byte shall not be all set to 0.
 — Bits b7 to b1 of the first subsequent byte, followed by bits b7 to b1 of each further subsequent byte,
up to and including bits b7 to b1 of the last subsequent byte encode a tag number.

### CODE REVIEW

**Comment by stv0g** [comment]
Hi @OmegaRelay,

thanks for your contribution :) However, I am not sure if we want to merge this.
The background is that the `tlv.Tag` is an alias for `uint` and I intended it not encode the tag number itself, but already its encoded form.

Take a look at the following example usage:
- https://github.com/cunicu/go-openpgp-card/blob/0901a5000cb31d97459d856c16be14dd23370e6f/constants.go#L449

I agree its a bit counterintuitive. But I found it the easiest way to both encode and handle both the tag number as well as the tag's class (bits b8 and b7).

I opted to use a `uint` as it allows me to define the tags as `const` values rather than `var` as I would have to with a `[]byte` slice.

I am open to your opinions and ideas here.

**Comment by OmegaRelay** [comment]
I realize I might have been a bit too quick to make a change I see now through testing and integrating the decoding that the user is expected to provide a correct tag during encoding that then is copied plainly I'll make an issue to discuss this further.

**Comment by stv0g** [comment]
> Would it be an option to instead add a helper function to create a tag something like `NewBERTag(value int, class Class) Tag` where then the constructed bit is again set in `EncodeBER()` directly in the `buf[0]`?

Yes definitely. I like this approach. Shouldnt we name the function `NewTag()` instead of `NewBERTag`?

**Comment by stv0g** [comment]
Ah, you are right. Those other encodings are in fact lacking the class bits.. Lets go with `NewBERTag` then :)

**Pull request closed without merging**
